name: Convert Bitbucket CI to Azure DevOps Pipeline

# Trigger manual para execução do workflow
on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Caminho do repositório Bitbucket (ex: brandaonetwork1/conv-yaml-out.git)'
        required: true
      destination_repo:
        description: 'Repositório de destino no GitHub (ex: BrandaoNetwork/conv-yaml-in)'
        required: true

jobs:
  convert_pipeline:
    runs-on: ubuntu-latest

    env:
      BITBUCKET_USER: ${{ secrets.BITBUCKET_USERNAME }}        # Nome de usuário do Bitbucket
      BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}    # Token/Senha do Bitbucket
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}            # Chave da API do OpenAI
      SOURCE_REPO: ${{ github.event.inputs.source_repo }}      # Caminho do repositório no Bitbucket
      DESTINATION_REPO: ${{ github.event.inputs.destination_repo }} # Repositório GitHub destino

    steps:

      # 1. Checkout do repositório atual no GitHub
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      # 2. Clone do repositório do Bitbucket
      - name: Clone Source Repository from Bitbucket
        run: |
          echo "Cloning Source Repository: $SOURCE_REPO"
          GIT_URL="https://${BITBUCKET_USER}:${BITBUCKET_PASSWORD}@bitbucket.org/${SOURCE_REPO}"
          echo "Generated URL: $GIT_URL"
          git clone $GIT_URL cloned-repo

      # 3. Listar arquivos do repositório clonado
      - name: List Files in Cloned Repository
        run: |
          echo "Files in cloned repository:"
          ls -la cloned-repo

      # 4. Converter o manifesto bitbucket-pipelines.yml usando OpenAI API
      - name: Convert Manifest with OpenAI API
        run: |
          cd cloned-repo
          if [ -f bitbucket-pipelines.yml ]; then
            echo "Found bitbucket-pipelines.yml, starting conversion..."
            BITBUCKET_CONTENT=$(cat bitbucket-pipelines.yml | sed 's/"/\\"/g' | tr '\n' ' ')
            
            RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "gpt-4",
                "messages": [
                  {"role": "system", "content": "You are a YAML conversion expert. Convert Bitbucket CI manifests to Azure DevOps pipeline manifests."},
                  {"role": "user", "content": "Convert the following Bitbucket CI pipeline YAML to Azure DevOps pipeline YAML:\n'"$BITBUCKET_CONTENT"'"}
                ]
              }')

            echo $RESPONSE | jq -r '.choices[0].message.content' > azure-pipeline-converted.yml
            echo "Conversion complete. File saved as azure-pipeline-converted.yml."
          else
            echo "No bitbucket-pipelines.yml found in repository. Exiting."
            exit 1
          fi

      # 5. Publicar o arquivo convertido como artefato
      - name: Upload Converted Pipeline as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: converted-azure-pipeline
          path: cloned-repo/azure-pipeline-converted.yml

      # 6. Enviar o arquivo convertido para o repositório de destino no GitHub
      - name: Push Converted Manifest to Destination Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático do GitHub Actions
        run: |
          echo "Pushing Converted Manifest to Destination Repository: $DESTINATION_REPO"

          # Configurar o usuário Git
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Clonar o repositório de destino
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${DESTINATION_REPO}.git destination-repo

          # Copiar o arquivo convertido para o repositório de destino
          cp cloned-repo/azure-pipeline-converted.yml destination-repo/

          # Commit e push do arquivo
          cd destination-repo
          git add azure-pipeline-converted.yml
          git commit -m "Add converted Azure DevOps pipeline manifest"
          git push origin main
